################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (9-2020-q2-update)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
P:/STM/STM32_SWI/i-cube-octave-wp77/en.x-cube-cellular_v6-0-0/STM32CubeExpansion_CELLULAR_V6.0.0/Drivers/BSP/B-L4S5I-IOT01A/stm32l4s5i_iot01.c \
P:/STM/STM32_SWI/i-cube-octave-wp77/en.x-cube-cellular_v6-0-0/STM32CubeExpansion_CELLULAR_V6.0.0/Drivers/BSP/B-L4S5I-IOT01A/stm32l4s5i_iot01_accelero.c \
P:/STM/STM32_SWI/i-cube-octave-wp77/en.x-cube-cellular_v6-0-0/STM32CubeExpansion_CELLULAR_V6.0.0/Drivers/BSP/B-L4S5I-IOT01A/stm32l4s5i_iot01_gyro.c \
P:/STM/STM32_SWI/i-cube-octave-wp77/en.x-cube-cellular_v6-0-0/STM32CubeExpansion_CELLULAR_V6.0.0/Drivers/BSP/B-L4S5I-IOT01A/stm32l4s5i_iot01_hsensor.c \
P:/STM/STM32_SWI/i-cube-octave-wp77/en.x-cube-cellular_v6-0-0/STM32CubeExpansion_CELLULAR_V6.0.0/Drivers/BSP/B-L4S5I-IOT01A/stm32l4s5i_iot01_magneto.c \
P:/STM/STM32_SWI/i-cube-octave-wp77/en.x-cube-cellular_v6-0-0/STM32CubeExpansion_CELLULAR_V6.0.0/Drivers/BSP/B-L4S5I-IOT01A/stm32l4s5i_iot01_psensor.c \
P:/STM/STM32_SWI/i-cube-octave-wp77/en.x-cube-cellular_v6-0-0/STM32CubeExpansion_CELLULAR_V6.0.0/Drivers/BSP/B-L4S5I-IOT01A/stm32l4s5i_iot01_tsensor.c 

OBJS += \
./Drivers/BSP/B-L4S5I-IOT01A/stm32l4s5i_iot01.o \
./Drivers/BSP/B-L4S5I-IOT01A/stm32l4s5i_iot01_accelero.o \
./Drivers/BSP/B-L4S5I-IOT01A/stm32l4s5i_iot01_gyro.o \
./Drivers/BSP/B-L4S5I-IOT01A/stm32l4s5i_iot01_hsensor.o \
./Drivers/BSP/B-L4S5I-IOT01A/stm32l4s5i_iot01_magneto.o \
./Drivers/BSP/B-L4S5I-IOT01A/stm32l4s5i_iot01_psensor.o \
./Drivers/BSP/B-L4S5I-IOT01A/stm32l4s5i_iot01_tsensor.o 

C_DEPS += \
./Drivers/BSP/B-L4S5I-IOT01A/stm32l4s5i_iot01.d \
./Drivers/BSP/B-L4S5I-IOT01A/stm32l4s5i_iot01_accelero.d \
./Drivers/BSP/B-L4S5I-IOT01A/stm32l4s5i_iot01_gyro.d \
./Drivers/BSP/B-L4S5I-IOT01A/stm32l4s5i_iot01_hsensor.d \
./Drivers/BSP/B-L4S5I-IOT01A/stm32l4s5i_iot01_magneto.d \
./Drivers/BSP/B-L4S5I-IOT01A/stm32l4s5i_iot01_psensor.d \
./Drivers/BSP/B-L4S5I-IOT01A/stm32l4s5i_iot01_tsensor.d 


# Each subdirectory must supply rules for building sources it contributes
Drivers/BSP/B-L4S5I-IOT01A/stm32l4s5i_iot01.o: P:/STM/STM32_SWI/i-cube-octave-wp77/en.x-cube-cellular_v6-0-0/STM32CubeExpansion_CELLULAR_V6.0.0/Drivers/BSP/B-L4S5I-IOT01A/stm32l4s5i_iot01.c Drivers/BSP/B-L4S5I-IOT01A/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32L4S5xx -DHAS_RTOS -DUSER_FLAG_MODEM_FORCE_NO_FLOW_CTRL -DHWREF_B_CELL_BG96_V2 '-DAPPLICATION_CONFIG_FILE="plf_cellular_app_sensors_config.h"' '-DAPPLICATION_THREAD_CONFIG_FILE="plf_cellular_app_sensors_thread_config.h"' -DDEBUG -DUSE_COM_MDM -c -I../../../../Core/Inc -I../../../../STM32_Cellular/Config -I../../../../STM32_Cellular/Target -I../../../../../../../Misc/Cmd/Inc -I../../../../../../../Misc/RTOS/FreeRTOS/Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../../../../../../../Middlewares/ST/STM32_Cellular/Core/AT_Core/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Core/Cellular_Service/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Core/Data_Cache/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Core/Error/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Core/Ipc/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Core/PPPosif/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Core/Runtime_Library/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Core/Rtosal/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Core/Trace/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Interface/Cellular_Ctrl/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Interface/Com/Inc -I../../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../../../../../../Middlewares/Third_Party/LwIP/system/arch -I../../../../../../../../Middlewares/Third_Party/LwIP/src/include -I../../../../../../../../Middlewares/Third_Party/LwIP/src/include/lwip/prot -I../../../../../../../../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../../../../../../../../Middlewares/Third_Party/LwIP/system -I../../../../../../../../Drivers/BSP/X_STMOD_PLUS_MODEMS/WP77/AT_modem_wp77/Inc -I../../../../../../../../Drivers/BSP/B-L4S5I-IOT01A/Components/Common -I../../../../../../../../Drivers/BSP/B-L4S5I-IOT01A -I../../../../../../../Misc/Samples/CellularSensors/Inc -I../../../../../../../../Drivers/BSP/B-L4S5I-IOT01A/Components/hts221 -I../../../../../../../../Drivers/BSP/B-L4S5I-IOT01A/Components/lis3mdl -I../../../../../../../../Drivers/BSP/B-L4S5I-IOT01A/Components/lps22hb -I../../../../../../../../Drivers/BSP/B-L4S5I-IOT01A/Components/lsm6dsl -I../../../../../../../../Middlewares/Third_Party/ORP_Octave/inc -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/BSP/B-L4S5I-IOT01A/stm32l4s5i_iot01.d" -MT"$@"  -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/B-L4S5I-IOT01A/stm32l4s5i_iot01_accelero.o: P:/STM/STM32_SWI/i-cube-octave-wp77/en.x-cube-cellular_v6-0-0/STM32CubeExpansion_CELLULAR_V6.0.0/Drivers/BSP/B-L4S5I-IOT01A/stm32l4s5i_iot01_accelero.c Drivers/BSP/B-L4S5I-IOT01A/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32L4S5xx -DHAS_RTOS -DUSER_FLAG_MODEM_FORCE_NO_FLOW_CTRL -DHWREF_B_CELL_BG96_V2 '-DAPPLICATION_CONFIG_FILE="plf_cellular_app_sensors_config.h"' '-DAPPLICATION_THREAD_CONFIG_FILE="plf_cellular_app_sensors_thread_config.h"' -DDEBUG -DUSE_COM_MDM -c -I../../../../Core/Inc -I../../../../STM32_Cellular/Config -I../../../../STM32_Cellular/Target -I../../../../../../../Misc/Cmd/Inc -I../../../../../../../Misc/RTOS/FreeRTOS/Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../../../../../../../Middlewares/ST/STM32_Cellular/Core/AT_Core/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Core/Cellular_Service/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Core/Data_Cache/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Core/Error/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Core/Ipc/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Core/PPPosif/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Core/Runtime_Library/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Core/Rtosal/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Core/Trace/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Interface/Cellular_Ctrl/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Interface/Com/Inc -I../../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../../../../../../Middlewares/Third_Party/LwIP/system/arch -I../../../../../../../../Middlewares/Third_Party/LwIP/src/include -I../../../../../../../../Middlewares/Third_Party/LwIP/src/include/lwip/prot -I../../../../../../../../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../../../../../../../../Middlewares/Third_Party/LwIP/system -I../../../../../../../../Drivers/BSP/X_STMOD_PLUS_MODEMS/WP77/AT_modem_wp77/Inc -I../../../../../../../../Drivers/BSP/B-L4S5I-IOT01A/Components/Common -I../../../../../../../../Drivers/BSP/B-L4S5I-IOT01A -I../../../../../../../Misc/Samples/CellularSensors/Inc -I../../../../../../../../Drivers/BSP/B-L4S5I-IOT01A/Components/hts221 -I../../../../../../../../Drivers/BSP/B-L4S5I-IOT01A/Components/lis3mdl -I../../../../../../../../Drivers/BSP/B-L4S5I-IOT01A/Components/lps22hb -I../../../../../../../../Drivers/BSP/B-L4S5I-IOT01A/Components/lsm6dsl -I../../../../../../../../Middlewares/Third_Party/ORP_Octave/inc -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/BSP/B-L4S5I-IOT01A/stm32l4s5i_iot01_accelero.d" -MT"$@"  -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/B-L4S5I-IOT01A/stm32l4s5i_iot01_gyro.o: P:/STM/STM32_SWI/i-cube-octave-wp77/en.x-cube-cellular_v6-0-0/STM32CubeExpansion_CELLULAR_V6.0.0/Drivers/BSP/B-L4S5I-IOT01A/stm32l4s5i_iot01_gyro.c Drivers/BSP/B-L4S5I-IOT01A/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32L4S5xx -DHAS_RTOS -DUSER_FLAG_MODEM_FORCE_NO_FLOW_CTRL -DHWREF_B_CELL_BG96_V2 '-DAPPLICATION_CONFIG_FILE="plf_cellular_app_sensors_config.h"' '-DAPPLICATION_THREAD_CONFIG_FILE="plf_cellular_app_sensors_thread_config.h"' -DDEBUG -DUSE_COM_MDM -c -I../../../../Core/Inc -I../../../../STM32_Cellular/Config -I../../../../STM32_Cellular/Target -I../../../../../../../Misc/Cmd/Inc -I../../../../../../../Misc/RTOS/FreeRTOS/Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../../../../../../../Middlewares/ST/STM32_Cellular/Core/AT_Core/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Core/Cellular_Service/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Core/Data_Cache/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Core/Error/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Core/Ipc/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Core/PPPosif/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Core/Runtime_Library/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Core/Rtosal/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Core/Trace/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Interface/Cellular_Ctrl/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Interface/Com/Inc -I../../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../../../../../../Middlewares/Third_Party/LwIP/system/arch -I../../../../../../../../Middlewares/Third_Party/LwIP/src/include -I../../../../../../../../Middlewares/Third_Party/LwIP/src/include/lwip/prot -I../../../../../../../../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../../../../../../../../Middlewares/Third_Party/LwIP/system -I../../../../../../../../Drivers/BSP/X_STMOD_PLUS_MODEMS/WP77/AT_modem_wp77/Inc -I../../../../../../../../Drivers/BSP/B-L4S5I-IOT01A/Components/Common -I../../../../../../../../Drivers/BSP/B-L4S5I-IOT01A -I../../../../../../../Misc/Samples/CellularSensors/Inc -I../../../../../../../../Drivers/BSP/B-L4S5I-IOT01A/Components/hts221 -I../../../../../../../../Drivers/BSP/B-L4S5I-IOT01A/Components/lis3mdl -I../../../../../../../../Drivers/BSP/B-L4S5I-IOT01A/Components/lps22hb -I../../../../../../../../Drivers/BSP/B-L4S5I-IOT01A/Components/lsm6dsl -I../../../../../../../../Middlewares/Third_Party/ORP_Octave/inc -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/BSP/B-L4S5I-IOT01A/stm32l4s5i_iot01_gyro.d" -MT"$@"  -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/B-L4S5I-IOT01A/stm32l4s5i_iot01_hsensor.o: P:/STM/STM32_SWI/i-cube-octave-wp77/en.x-cube-cellular_v6-0-0/STM32CubeExpansion_CELLULAR_V6.0.0/Drivers/BSP/B-L4S5I-IOT01A/stm32l4s5i_iot01_hsensor.c Drivers/BSP/B-L4S5I-IOT01A/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32L4S5xx -DHAS_RTOS -DUSER_FLAG_MODEM_FORCE_NO_FLOW_CTRL -DHWREF_B_CELL_BG96_V2 '-DAPPLICATION_CONFIG_FILE="plf_cellular_app_sensors_config.h"' '-DAPPLICATION_THREAD_CONFIG_FILE="plf_cellular_app_sensors_thread_config.h"' -DDEBUG -DUSE_COM_MDM -c -I../../../../Core/Inc -I../../../../STM32_Cellular/Config -I../../../../STM32_Cellular/Target -I../../../../../../../Misc/Cmd/Inc -I../../../../../../../Misc/RTOS/FreeRTOS/Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../../../../../../../Middlewares/ST/STM32_Cellular/Core/AT_Core/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Core/Cellular_Service/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Core/Data_Cache/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Core/Error/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Core/Ipc/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Core/PPPosif/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Core/Runtime_Library/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Core/Rtosal/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Core/Trace/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Interface/Cellular_Ctrl/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Interface/Com/Inc -I../../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../../../../../../Middlewares/Third_Party/LwIP/system/arch -I../../../../../../../../Middlewares/Third_Party/LwIP/src/include -I../../../../../../../../Middlewares/Third_Party/LwIP/src/include/lwip/prot -I../../../../../../../../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../../../../../../../../Middlewares/Third_Party/LwIP/system -I../../../../../../../../Drivers/BSP/X_STMOD_PLUS_MODEMS/WP77/AT_modem_wp77/Inc -I../../../../../../../../Drivers/BSP/B-L4S5I-IOT01A/Components/Common -I../../../../../../../../Drivers/BSP/B-L4S5I-IOT01A -I../../../../../../../Misc/Samples/CellularSensors/Inc -I../../../../../../../../Drivers/BSP/B-L4S5I-IOT01A/Components/hts221 -I../../../../../../../../Drivers/BSP/B-L4S5I-IOT01A/Components/lis3mdl -I../../../../../../../../Drivers/BSP/B-L4S5I-IOT01A/Components/lps22hb -I../../../../../../../../Drivers/BSP/B-L4S5I-IOT01A/Components/lsm6dsl -I../../../../../../../../Middlewares/Third_Party/ORP_Octave/inc -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/BSP/B-L4S5I-IOT01A/stm32l4s5i_iot01_hsensor.d" -MT"$@"  -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/B-L4S5I-IOT01A/stm32l4s5i_iot01_magneto.o: P:/STM/STM32_SWI/i-cube-octave-wp77/en.x-cube-cellular_v6-0-0/STM32CubeExpansion_CELLULAR_V6.0.0/Drivers/BSP/B-L4S5I-IOT01A/stm32l4s5i_iot01_magneto.c Drivers/BSP/B-L4S5I-IOT01A/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32L4S5xx -DHAS_RTOS -DUSER_FLAG_MODEM_FORCE_NO_FLOW_CTRL -DHWREF_B_CELL_BG96_V2 '-DAPPLICATION_CONFIG_FILE="plf_cellular_app_sensors_config.h"' '-DAPPLICATION_THREAD_CONFIG_FILE="plf_cellular_app_sensors_thread_config.h"' -DDEBUG -DUSE_COM_MDM -c -I../../../../Core/Inc -I../../../../STM32_Cellular/Config -I../../../../STM32_Cellular/Target -I../../../../../../../Misc/Cmd/Inc -I../../../../../../../Misc/RTOS/FreeRTOS/Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../../../../../../../Middlewares/ST/STM32_Cellular/Core/AT_Core/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Core/Cellular_Service/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Core/Data_Cache/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Core/Error/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Core/Ipc/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Core/PPPosif/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Core/Runtime_Library/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Core/Rtosal/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Core/Trace/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Interface/Cellular_Ctrl/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Interface/Com/Inc -I../../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../../../../../../Middlewares/Third_Party/LwIP/system/arch -I../../../../../../../../Middlewares/Third_Party/LwIP/src/include -I../../../../../../../../Middlewares/Third_Party/LwIP/src/include/lwip/prot -I../../../../../../../../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../../../../../../../../Middlewares/Third_Party/LwIP/system -I../../../../../../../../Drivers/BSP/X_STMOD_PLUS_MODEMS/WP77/AT_modem_wp77/Inc -I../../../../../../../../Drivers/BSP/B-L4S5I-IOT01A/Components/Common -I../../../../../../../../Drivers/BSP/B-L4S5I-IOT01A -I../../../../../../../Misc/Samples/CellularSensors/Inc -I../../../../../../../../Drivers/BSP/B-L4S5I-IOT01A/Components/hts221 -I../../../../../../../../Drivers/BSP/B-L4S5I-IOT01A/Components/lis3mdl -I../../../../../../../../Drivers/BSP/B-L4S5I-IOT01A/Components/lps22hb -I../../../../../../../../Drivers/BSP/B-L4S5I-IOT01A/Components/lsm6dsl -I../../../../../../../../Middlewares/Third_Party/ORP_Octave/inc -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/BSP/B-L4S5I-IOT01A/stm32l4s5i_iot01_magneto.d" -MT"$@"  -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/B-L4S5I-IOT01A/stm32l4s5i_iot01_psensor.o: P:/STM/STM32_SWI/i-cube-octave-wp77/en.x-cube-cellular_v6-0-0/STM32CubeExpansion_CELLULAR_V6.0.0/Drivers/BSP/B-L4S5I-IOT01A/stm32l4s5i_iot01_psensor.c Drivers/BSP/B-L4S5I-IOT01A/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32L4S5xx -DHAS_RTOS -DUSER_FLAG_MODEM_FORCE_NO_FLOW_CTRL -DHWREF_B_CELL_BG96_V2 '-DAPPLICATION_CONFIG_FILE="plf_cellular_app_sensors_config.h"' '-DAPPLICATION_THREAD_CONFIG_FILE="plf_cellular_app_sensors_thread_config.h"' -DDEBUG -DUSE_COM_MDM -c -I../../../../Core/Inc -I../../../../STM32_Cellular/Config -I../../../../STM32_Cellular/Target -I../../../../../../../Misc/Cmd/Inc -I../../../../../../../Misc/RTOS/FreeRTOS/Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../../../../../../../Middlewares/ST/STM32_Cellular/Core/AT_Core/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Core/Cellular_Service/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Core/Data_Cache/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Core/Error/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Core/Ipc/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Core/PPPosif/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Core/Runtime_Library/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Core/Rtosal/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Core/Trace/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Interface/Cellular_Ctrl/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Interface/Com/Inc -I../../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../../../../../../Middlewares/Third_Party/LwIP/system/arch -I../../../../../../../../Middlewares/Third_Party/LwIP/src/include -I../../../../../../../../Middlewares/Third_Party/LwIP/src/include/lwip/prot -I../../../../../../../../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../../../../../../../../Middlewares/Third_Party/LwIP/system -I../../../../../../../../Drivers/BSP/X_STMOD_PLUS_MODEMS/WP77/AT_modem_wp77/Inc -I../../../../../../../../Drivers/BSP/B-L4S5I-IOT01A/Components/Common -I../../../../../../../../Drivers/BSP/B-L4S5I-IOT01A -I../../../../../../../Misc/Samples/CellularSensors/Inc -I../../../../../../../../Drivers/BSP/B-L4S5I-IOT01A/Components/hts221 -I../../../../../../../../Drivers/BSP/B-L4S5I-IOT01A/Components/lis3mdl -I../../../../../../../../Drivers/BSP/B-L4S5I-IOT01A/Components/lps22hb -I../../../../../../../../Drivers/BSP/B-L4S5I-IOT01A/Components/lsm6dsl -I../../../../../../../../Middlewares/Third_Party/ORP_Octave/inc -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/BSP/B-L4S5I-IOT01A/stm32l4s5i_iot01_psensor.d" -MT"$@"  -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/B-L4S5I-IOT01A/stm32l4s5i_iot01_tsensor.o: P:/STM/STM32_SWI/i-cube-octave-wp77/en.x-cube-cellular_v6-0-0/STM32CubeExpansion_CELLULAR_V6.0.0/Drivers/BSP/B-L4S5I-IOT01A/stm32l4s5i_iot01_tsensor.c Drivers/BSP/B-L4S5I-IOT01A/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32L4S5xx -DHAS_RTOS -DUSER_FLAG_MODEM_FORCE_NO_FLOW_CTRL -DHWREF_B_CELL_BG96_V2 '-DAPPLICATION_CONFIG_FILE="plf_cellular_app_sensors_config.h"' '-DAPPLICATION_THREAD_CONFIG_FILE="plf_cellular_app_sensors_thread_config.h"' -DDEBUG -DUSE_COM_MDM -c -I../../../../Core/Inc -I../../../../STM32_Cellular/Config -I../../../../STM32_Cellular/Target -I../../../../../../../Misc/Cmd/Inc -I../../../../../../../Misc/RTOS/FreeRTOS/Inc -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../../../../../../../../Middlewares/ST/STM32_Cellular/Core/AT_Core/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Core/Cellular_Service/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Core/Data_Cache/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Core/Error/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Core/Ipc/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Core/PPPosif/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Core/Runtime_Library/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Core/Rtosal/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Core/Trace/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Interface/Cellular_Ctrl/Inc -I../../../../../../../../Middlewares/ST/STM32_Cellular/Interface/Com/Inc -I../../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../../../../../../Middlewares/Third_Party/LwIP/system/arch -I../../../../../../../../Middlewares/Third_Party/LwIP/src/include -I../../../../../../../../Middlewares/Third_Party/LwIP/src/include/lwip/prot -I../../../../../../../../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../../../../../../../../Middlewares/Third_Party/LwIP/system -I../../../../../../../../Drivers/BSP/X_STMOD_PLUS_MODEMS/WP77/AT_modem_wp77/Inc -I../../../../../../../../Drivers/BSP/B-L4S5I-IOT01A/Components/Common -I../../../../../../../../Drivers/BSP/B-L4S5I-IOT01A -I../../../../../../../Misc/Samples/CellularSensors/Inc -I../../../../../../../../Drivers/BSP/B-L4S5I-IOT01A/Components/hts221 -I../../../../../../../../Drivers/BSP/B-L4S5I-IOT01A/Components/lis3mdl -I../../../../../../../../Drivers/BSP/B-L4S5I-IOT01A/Components/lps22hb -I../../../../../../../../Drivers/BSP/B-L4S5I-IOT01A/Components/lsm6dsl -I../../../../../../../../Middlewares/Third_Party/ORP_Octave/inc -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/BSP/B-L4S5I-IOT01A/stm32l4s5i_iot01_tsensor.d" -MT"$@"  -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

